### ISSUE TITLE
No way to select skins (Can't find the settings menu)

### ISSUE THREAD

**Issue by wyatt8740** [dparnell/i48#3]
I'm going to prefix this by saying that I have almost no knowledge of ObjC.

I saw the settings menu in a screenshot on your blog, but I can't figure out how to get to that screen.

I don't really like the default photo of an HP48 and prefer the 'froux' skin. The only way I was able to actually make the app use that skin was to substitute the '_froux_*' directories in the compiled app (I don't have a Mac, and it's a real pain to build it in a VM, and my VM is running 10.8 so I don't know if XCode is even compatible anymore).

Thanks for the app, and especially for making it free and open source, by the way. I'm a huge fan of my HP-28S and I appreciate having something similar on all my devices - iOS was the last that really needed one.

(Also, I looked at your blog briefly; if you need an Atari Joystick, I have several in the 2600 style if you'd like one. Also note that in a pinch you can use a Sega Genesis/Mega Drive controller with most Atari-style joystick ports. I use one on my [physical] Amiga 500 occasionally.)

**Comment by dparnell** [comment]
The skin can be selected via the i48 section in the system settings app. When I wrote i48 this was the way Apple wanted apps to present settings to the user. These days most apps just have the settings inside.
i48 should be able to compile under Xcode on 10.8, but I've not tried it recently.
As for the joystick, I managed to get one on ebay 😄

**Comment by wyatt8740** [comment]
Ahhh, I've been away from iOS for too long (I primarily use Android - my Pixel 2) - I'd forgotten about that function of the settings app. Thanks!
